title: JSALT 2017 MT Team
description: The 2017 Jelinek Summer Workshop on Speech and Language Technology (JSALT) at CMU
author: The JSALT 2017 Organizer

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
